from . import test_approval
from . import test_ir_model
from . import test_report_editor
from . import test_ui
from . import test_view_normalization
from . import test_view_editor
from . import test_export
from . import test_form_only_policy
from . import test_keyed_xml_differ
from . import test_workflow_studio_bpmn
from . import test_module_state
from . import test_workflow_studio_import_zip
from . import test_workflow_studio_model_options
from . import test_ui_form_only_tours
from . import test_exit_clearance_demo
from . import test_quick_start_wizard
from . import test_business_case_regression
from . import test_required_domain_guardrails
from . import test_category_sequence
from . import test_bpmn_editor_palette
