# -*- coding: utf-8 -*-

from odoo import api, models, _
from odoo.exceptions import UserError
from odoo.addons.base.models.ir_module import assert_log_admin_access, ACTION_DICT

WORKFLOW_STUDIO_CUSTOMIZATION_MODULE = "workflow_studio_customization"
WORKFLOW_STUDIO_CUSTOMIZATION_TITLE = "Workflow Studio customizations"
WORKFLOW_STUDIO_CUSTOMIZATION_DESCRIPTION = """This module has been generated by Workflow Studio.
It contains the apps created with Workflow Studio and the customizations of existing apps."""


class IrModuleModule(models.Model):
    _inherit = 'ir.module.module'

    @api.model
    def _workflow_studio_customization_values(self):
        return {
            "application": False,
            "category_id": self.env.ref("workflow_engine.module_category_workflow").id,
            "shortdesc": WORKFLOW_STUDIO_CUSTOMIZATION_TITLE,
            "description": WORKFLOW_STUDIO_CUSTOMIZATION_DESCRIPTION,
            "state": "installed",
            "imported": True,
            "author": self.env.company.name,
            "icon": "/base/static/description/icon.png",
            "license": "OPL-1",
        }

    @api.model
    def _workflow_studio_ensure_customization_module_consistency(self, module):
        module = module.sudo().exists()
        if not module:
            return module

        values = {}
        target_values = self._workflow_studio_customization_values()
        for field_name, target_value in target_values.items():
            field = module._fields.get(field_name)
            current_value = getattr(module, field_name)
            if field and field.type == "many2one":
                current_value = current_value.id
            if current_value != target_value:
                values[field_name] = target_value
        if values:
            module.write(values)

        if module.dependencies_id:
            module._update_dependencies([])
        return module

    @api.model
    def get_studio_module(self):
        """ Returns the Studio module gathering all customizations done in
            Studio (freshly created apps and customizations of existing apps).
            Creates that module if it doesn't exist yet.
        """
        studio_module = self.search([('name', '=', WORKFLOW_STUDIO_CUSTOMIZATION_MODULE)], limit=1)
        if not studio_module:
            studio_module = self.create(
                dict(name=WORKFLOW_STUDIO_CUSTOMIZATION_MODULE, **self._workflow_studio_customization_values())
            )
        return self._workflow_studio_ensure_customization_module_consistency(studio_module)

    @assert_log_admin_access
    @api.model
    def update_list(self):
        result = super().update_list()
        module = self.search([("name", "=", WORKFLOW_STUDIO_CUSTOMIZATION_MODULE)], limit=1)
        if module:
            self._workflow_studio_ensure_customization_module_consistency(module)
        return result

    @assert_log_admin_access
    def button_install(self):
        custom_module = self.filtered(lambda module: module.name == WORKFLOW_STUDIO_CUSTOMIZATION_MODULE)
        if custom_module:
            self._workflow_studio_ensure_customization_module_consistency(custom_module)
        remaining_modules = self - custom_module
        if not remaining_modules:
            return True
        return super(IrModuleModule, remaining_modules).button_install()

    @assert_log_admin_access
    def button_upgrade(self):
        if not self:
            return
        Dependency = self.env['ir.module.module.dependency']
        customization_module = self.search([("name", "=", WORKFLOW_STUDIO_CUSTOMIZATION_MODULE)], limit=1)
        if customization_module:
            self._workflow_studio_ensure_customization_module_consistency(customization_module)
        self.update_list()

        todo = list(self)
        if 'base' in self.mapped('name'):
            # If an installed module is only present in the dependency graph through
            # a new, uninstalled dependency, it will not have been selected yet.
            # An update of 'base' should also update these modules, and as a consequence,
            # install the new dependency.
            todo.extend(self.search([
                ('state', '=', 'installed'),
                ('name', '!=', 'studio_customization'),
                ('name', '!=', 'workflow_studio_customization'),
                ('id', 'not in', self.ids),
            ]))
        i = 0
        while i < len(todo):
            module = todo[i]
            i += 1
            if module.state not in ('installed', 'to upgrade'):
                raise UserError(_("Cannot upgrade module “%s”. It is not installed.", module.name))
            if self.get_module_info(module.name).get("installable", True):
                self.check_external_dependencies(module.name, 'to upgrade')
            for dep in Dependency.search([('name', '=', module.name)]):
                if (
                        dep.module_id.state == 'installed'
                        and dep.module_id not in todo
                        and dep.module_id.name != 'studio_customization'
                        and dep.module_id.name != 'workflow_studio_customization'
                ):
                    todo.append(dep.module_id)

        self.browse(module.id for module in todo).write({'state': 'to upgrade'})

        to_install = []
        for module in todo:
            if not self.get_module_info(module.name).get("installable", True):
                continue
            for dep in module.dependencies_id:
                if dep.state == 'unknown':
                    raise UserError(_(
                        'You try to upgrade the module %(module)s that depends on the module: %(dependency)s.\n'
                        'But this module is not available in your system.',
                        module=module.name,
                        dependency=dep.name
                    ))
                if dep.state == 'uninstalled':
                    if dep.name == WORKFLOW_STUDIO_CUSTOMIZATION_MODULE:
                        continue
                    to_install += self.search([('name', '=', dep.name)]).ids

        self.browse(to_install).button_install()
        # Keep imported modules stable across upgrades (base_import_module behavior),
        # and enforce the Workflow Studio customization module consistency.
        imported_upgrades = self.search([('imported', '=', True), ('state', '=', 'to upgrade')])
        if imported_upgrades:
            imported_upgrades.write({'state': 'installed'})
        customization_module = self.search([("name", "=", WORKFLOW_STUDIO_CUSTOMIZATION_MODULE)], limit=1)
        if customization_module:
            self._workflow_studio_ensure_customization_module_consistency(customization_module)
        return dict(ACTION_DICT, name=_('Apply Schedule Upgrade'))
