{
    'name': 'Workflow',
    'version': '3.27',
    'category': 'Workflow',
    'author': 'Programming Team',
    'sequence': 100,
    'summary': 'Create and validate approvals requests',
    'depends': ['mail', 'hr', 'base_automation', 'naga_base'],
    'data': [
        # for security
        'security/groups.xml',
        'security/access_approval_approver.xml',
        'security/access_approval_category.xml',
        'security/access_approval_graph.xml',
        'security/access_approval_category_approver.xml',
        'security/access_approval_category_version.xml',
        'security/access_approval_request.xml',
        'security/access_workflow_approval_group.xml',
        'security/access_workflow_approval_group_line.xml',
        'security/access_workflow_approval_group_team.xml',
        'security/access_workflow_category_task_approval_group.xml',
        'security/access_workflow_category_version_meta_field.xml',
        'security/access_workflow_category_version_meta_task_action.xml',
        'security/access_workflow_category_version_meta_task.xml',
        'security/access_workflow_category_version_meta_task_map.xml',
        "security/acesss_rule.xml",
        "security/access_workflow_runtime.xml",
        "security/rule_workflow_runtime.xml",
        'security/access_ir_model.xml',
        'security/access_delegate_wizard.xml',
        'security/access_workflow_access_policy.xml',
        'security/access_workflow_default_visible_field.xml',
        'security/access_workflow_dryrun_wizard.xml',
        'security/access_workflow_approval_user_matrix_report.xml',

        'wizard/ir_action_windows.xml',
        'wizard/ir_ui_view.xml',

        # for data
        'data/record_rule.xml',
        'data/workflow_default_visible_field.xml',
        'data/mail_message_subtype.xml',
        'data/mail_activity_type.xml',
        'data/mail_activity_templates.xml',
        'data/smtp_server.xml',
        'data/ir_config_parameter.xml',
        
        'data/approver_groups.xml',
        'data/action_server.xml',
        'data/automation_rule.xml',
        'data/workflow_runtime_cron.xml',
        'data/mail_template.xml',
        'data/hierachy_data.xml',
        'report/paperformat.xml',

        # for view
        'views/ir_model_views.xml',
        'views/workflow_confirm_wizard_views.xml',
        
        'views/workflow_approval_category_views.xml',
        'views/workflow_approval_category_approver_views.xml',
        'report/approval_request_report.xml',
        'views/workflow_approval_base_request_views.xml',
        'views/res_config_settings_views.xml',
        'views/ir_action_windows.xml',
        'views/res_users_views.xml',
        'views/requestor_import_wizard_views.xml',
        'views/workflow_access_policy_views.xml',
        'views/workflow_visibility_scope_views.xml',
        'views/workflow_default_visible_field_views.xml',
        'views/workflow_approval_user_matrix_report_views.xml',
        'views/workflow_approval_directory_report_views.xml',
        'views/workflow_runtime_security_views.xml',
        'views/ir_menu.xml',
        'views/ir_menu_overrides.xml',
        'views/workflow_approval_report_views.xml',
        'views/workflow_approval_action_views.xml',
        'views/workflow_dryrun_wizard_views.xml',

        # report
        'report/report_base_layout.xml',
    ],
    'demo': [
        'demo/jobs.xml',
        'demo/users.xml',
        'demo/departments.xml',
        'demo/job_assignments.xml'
    ],
    'application': True,
    'installable': True,
    'assets': {
        'web.assets_backend': [
            'workflow_engine/static/lib/bpmn-js/**/*.css',
            # 'workflow_engine/static/lib/bpmn-js/custom_bpmn_renderer.js',
            'workflow_engine/static/src/**/*',
            ('remove', 'workflow_engine/static/src/**/**/*.dark.scss'),
            'workflow_engine/static/src/web/confirm_wizard/confirm_wizard.js',
            'workflow_engine/static/src/web/twofa_dialog/twofa_dialog.js',
            'workflow_engine/static/src/web/twofa_dialog/twofa_dialog.scss',
        ],
        'web.assets_tests': [
            'workflow_engine/static/tests/tours/**/*',
        ],
        "web.assets_web_dark": [
            'workflow_engine/static/src/**/**/*.dark.scss',
        ],
        'web.assets_qweb': [
            'workflow_engine/static/src/web/confirm_wizard/confirm_wizard.xml',
            'workflow_engine/static/src/web/patches/wf_form_runtime_field_state.xml',
            'workflow_engine/static/src/web/twofa_dialog/twofa_dialog.xml',
        ],

        'web.assets_unit_tests': [
            'workflow_engine/static/tests/**/*',
            ('remove', 'workflow_engine/static/tests/tours/**/*'),
        ],
    },
    'license': 'LGPL-3',
}
